# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Run Python script
      id: hello_script
      run: echo "::set-output name=result::$(python print.py)"

    - name: Check output
      run: |
        if [ "${{ steps.hello_script.outputs.result }}" == "hello actions" ]; then
          echo "Output is correct";
        fi

      
